/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link HelloWebWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractHelloWebWebModule extends DefaultWebModule {

}
