/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.HelloWebStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class HelloWebStandaloneSetup extends HelloWebStandaloneSetupGenerated {
  public static void doSetup() {
    new HelloWebStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
