/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.helloweb.ui.internal.HellowebActivator;

public class HelloWebUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HellowebActivator.getInstance().getInjector("org.xtext.example.mydsl.HelloWeb");
	}

}
