/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.web;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import org.eclipse.xtext.web.server.XtextServiceDispatcher;
import org.eclipse.xtext.web.server.persistence.IResourceBaseProvider;
import org.eclipse.xtext.web.server.persistence.IServerResourceHandler;
import org.eclipse.xtext.web.server.persistence.ResourceBaseProviderImpl;
import org.xtext.example.mydsl.web.AbstractHelloWebWebModule;
import org.xtext.example.mydsl.web.HelloWebResourceHandler;
import org.xtext.example.mydsl.web.HelloWebServiceDispatcher;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class HelloWebWebModule extends AbstractHelloWebWebModule {
  public Class<? extends IServerResourceHandler> bindIServerResourceHandler() {
    return HelloWebResourceHandler.class;
  }
  
  public Class<? extends XtextServiceDispatcher> bindXtextServiceDispatcher() {
    return HelloWebServiceDispatcher.class;
  }
  
  public void configureIResourceBaseProvider(final Binder binder) {
    AnnotatedBindingBuilder<IResourceBaseProvider> _bind = binder.<IResourceBaseProvider>bind(IResourceBaseProvider.class);
    ResourceBaseProviderImpl _resourceBaseProviderImpl = new ResourceBaseProviderImpl("./booster-files");
    _bind.toInstance(_resourceBaseProviderImpl);
  }
}
