/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.HelloWebRuntimeModule;
import org.xtext.example.mydsl.HelloWebStandaloneSetup;
import org.xtext.example.mydsl.ide.HelloWebIdeModule;
import org.xtext.example.mydsl.web.HelloWebWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class HelloWebWebSetup extends HelloWebStandaloneSetup {
  @Override
  public Injector createInjector() {
    HelloWebRuntimeModule _helloWebRuntimeModule = new HelloWebRuntimeModule();
    HelloWebIdeModule _helloWebIdeModule = new HelloWebIdeModule();
    HelloWebWebModule _helloWebWebModule = new HelloWebWebModule();
    return Guice.createInjector(Modules2.mixin(_helloWebRuntimeModule, _helloWebIdeModule, _helloWebWebModule));
  }
}
