/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends SuperCommand
{
} // Command
