/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.helloWeb.FunctionName#getFunc_name <em>Func name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getFunctionName()
 * @model
 * @generated
 */
public interface FunctionName extends SuperCommand
{
  /**
   * Returns the value of the '<em><b>Func name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func name</em>' attribute.
   * @see #setFunc_name(String)
   * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getFunctionName_Func_name()
   * @model
   * @generated
   */
  String getFunc_name();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.helloWeb.FunctionName#getFunc_name <em>Func name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func name</em>' attribute.
   * @see #getFunc_name()
   * @generated
   */
  void setFunc_name(String value);

} // FunctionName
