/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.helloWeb.HelloWebFactory
 * @model kind="package"
 * @generated
 */
public interface HelloWebPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "helloWeb";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/HelloWeb";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "helloWeb";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HelloWebPackage eINSTANCE = org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.ProgramImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__MAIN = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.MainImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getMain()
   * @generated
   */
  int MAIN = 1;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__COMMANDS = 0;

  /**
   * The feature id for the '<em><b>Takeoff</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__TAKEOFF = 1;

  /**
   * The feature id for the '<em><b>Land</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__LAND = 2;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.RecordedFlightImpl <em>Recorded Flight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.RecordedFlightImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRecordedFlight()
   * @generated
   */
  int RECORDED_FLIGHT = 2;

  /**
   * The feature id for the '<em><b>Video name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORDED_FLIGHT__VIDEO_NAME = 0;

  /**
   * The number of structural features of the '<em>Recorded Flight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECORDED_FLIGHT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.UserFunctionImpl <em>User Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.UserFunctionImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getUserFunction()
   * @generated
   */
  int USER_FUNCTION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Func</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION__FUNC = 1;

  /**
   * The number of structural features of the '<em>User Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int USER_FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.FeatureMatchImpl <em>Feature Match</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.FeatureMatchImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getFeatureMatch()
   * @generated
   */
  int FEATURE_MATCH = 4;

  /**
   * The feature id for the '<em><b>Image name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MATCH__IMAGE_NAME = 0;

  /**
   * The number of structural features of the '<em>Feature Match</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MATCH_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.SuperCommandImpl <em>Super Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.SuperCommandImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getSuperCommand()
   * @generated
   */
  int SUPER_COMMAND = 5;

  /**
   * The number of structural features of the '<em>Super Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUPER_COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.CommandImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 6;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = SUPER_COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.SnapshotImpl <em>Snapshot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.SnapshotImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getSnapshot()
   * @generated
   */
  int SNAPSHOT = 7;

  /**
   * The feature id for the '<em><b>Image name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SNAPSHOT__IMAGE_NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Snapshot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SNAPSHOT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.UpImpl <em>Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.UpImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getUp()
   * @generated
   */
  int UP = 8;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UP_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.DownImpl <em>Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.DownImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getDown()
   * @generated
   */
  int DOWN = 9;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOWN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.LeftImpl <em>Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.LeftImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getLeft()
   * @generated
   */
  int LEFT = 10;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.RightImpl <em>Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.RightImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRight()
   * @generated
   */
  int RIGHT = 11;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.ForwardImpl <em>Forward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.ForwardImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getForward()
   * @generated
   */
  int FORWARD = 12;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Forward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.BackwardImpl <em>Backward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.BackwardImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getBackward()
   * @generated
   */
  int BACKWARD = 13;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Backward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BACKWARD_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.RotateLImpl <em>Rotate L</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.RotateLImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRotateL()
   * @generated
   */
  int ROTATE_L = 14;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate L</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_L_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.RotateRImpl <em>Rotate R</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.RotateRImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRotateR()
   * @generated
   */
  int ROTATE_R = 15;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rotate R</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_R_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.WaitImpl <em>Wait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.WaitImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getWait()
   * @generated
   */
  int WAIT = 16;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT__MILLISECONDS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Wait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAIT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.helloWeb.impl.FunctionNameImpl <em>Function Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.helloWeb.impl.FunctionNameImpl
   * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getFunctionName()
   * @generated
   */
  int FUNCTION_NAME = 17;

  /**
   * The feature id for the '<em><b>Func name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME__FUNC_NAME = SUPER_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Function Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_NAME_FEATURE_COUNT = SUPER_COMMAND_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.helloWeb.Program#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Program#getMain()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Main();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.helloWeb.Main#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Main#getCommands()
   * @see #getMain()
   * @generated
   */
  EReference getMain_Commands();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.helloWeb.Main#getTakeoff <em>Takeoff</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Takeoff</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Main#getTakeoff()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Takeoff();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.helloWeb.Main#getLand <em>Land</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Land</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Main#getLand()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Land();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.RecordedFlight <em>Recorded Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Recorded Flight</em>'.
   * @see org.xtext.example.mydsl.helloWeb.RecordedFlight
   * @generated
   */
  EClass getRecordedFlight();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.RecordedFlight#getVideo_name <em>Video name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Video name</em>'.
   * @see org.xtext.example.mydsl.helloWeb.RecordedFlight#getVideo_name()
   * @see #getRecordedFlight()
   * @generated
   */
  EAttribute getRecordedFlight_Video_name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.UserFunction <em>User Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>User Function</em>'.
   * @see org.xtext.example.mydsl.helloWeb.UserFunction
   * @generated
   */
  EClass getUserFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.UserFunction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.helloWeb.UserFunction#getName()
   * @see #getUserFunction()
   * @generated
   */
  EAttribute getUserFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.helloWeb.UserFunction#getFunc <em>Func</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Func</em>'.
   * @see org.xtext.example.mydsl.helloWeb.UserFunction#getFunc()
   * @see #getUserFunction()
   * @generated
   */
  EReference getUserFunction_Func();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.FeatureMatch <em>Feature Match</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature Match</em>'.
   * @see org.xtext.example.mydsl.helloWeb.FeatureMatch
   * @generated
   */
  EClass getFeatureMatch();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.FeatureMatch#getImage_name <em>Image name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Image name</em>'.
   * @see org.xtext.example.mydsl.helloWeb.FeatureMatch#getImage_name()
   * @see #getFeatureMatch()
   * @generated
   */
  EAttribute getFeatureMatch_Image_name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.SuperCommand <em>Super Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Super Command</em>'.
   * @see org.xtext.example.mydsl.helloWeb.SuperCommand
   * @generated
   */
  EClass getSuperCommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Snapshot <em>Snapshot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Snapshot</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Snapshot
   * @generated
   */
  EClass getSnapshot();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Snapshot#getImage_name <em>Image name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Image name</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Snapshot#getImage_name()
   * @see #getSnapshot()
   * @generated
   */
  EAttribute getSnapshot_Image_name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Up <em>Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Up</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Up
   * @generated
   */
  EClass getUp();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Up#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Up#getMilliseconds()
   * @see #getUp()
   * @generated
   */
  EAttribute getUp_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Down <em>Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Down</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Down
   * @generated
   */
  EClass getDown();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Down#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Down#getMilliseconds()
   * @see #getDown()
   * @generated
   */
  EAttribute getDown_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Left <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Left
   * @generated
   */
  EClass getLeft();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Left#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Left#getMilliseconds()
   * @see #getLeft()
   * @generated
   */
  EAttribute getLeft_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Right <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Right
   * @generated
   */
  EClass getRight();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Right#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Right#getMilliseconds()
   * @see #getRight()
   * @generated
   */
  EAttribute getRight_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Forward <em>Forward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Forward</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Forward
   * @generated
   */
  EClass getForward();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Forward#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Forward#getMilliseconds()
   * @see #getForward()
   * @generated
   */
  EAttribute getForward_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Backward <em>Backward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Backward</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Backward
   * @generated
   */
  EClass getBackward();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Backward#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Backward#getMilliseconds()
   * @see #getBackward()
   * @generated
   */
  EAttribute getBackward_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.RotateL <em>Rotate L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate L</em>'.
   * @see org.xtext.example.mydsl.helloWeb.RotateL
   * @generated
   */
  EClass getRotateL();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.RotateL#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.RotateL#getMilliseconds()
   * @see #getRotateL()
   * @generated
   */
  EAttribute getRotateL_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.RotateR <em>Rotate R</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate R</em>'.
   * @see org.xtext.example.mydsl.helloWeb.RotateR
   * @generated
   */
  EClass getRotateR();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.RotateR#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.RotateR#getMilliseconds()
   * @see #getRotateR()
   * @generated
   */
  EAttribute getRotateR_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.Wait <em>Wait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Wait</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Wait
   * @generated
   */
  EClass getWait();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.Wait#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see org.xtext.example.mydsl.helloWeb.Wait#getMilliseconds()
   * @see #getWait()
   * @generated
   */
  EAttribute getWait_Milliseconds();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.helloWeb.FunctionName <em>Function Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Name</em>'.
   * @see org.xtext.example.mydsl.helloWeb.FunctionName
   * @generated
   */
  EClass getFunctionName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.helloWeb.FunctionName#getFunc_name <em>Func name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Func name</em>'.
   * @see org.xtext.example.mydsl.helloWeb.FunctionName#getFunc_name()
   * @see #getFunctionName()
   * @generated
   */
  EAttribute getFunctionName_Func_name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HelloWebFactory getHelloWebFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.ProgramImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__MAIN = eINSTANCE.getProgram_Main();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.MainImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN__COMMANDS = eINSTANCE.getMain_Commands();

    /**
     * The meta object literal for the '<em><b>Takeoff</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__TAKEOFF = eINSTANCE.getMain_Takeoff();

    /**
     * The meta object literal for the '<em><b>Land</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__LAND = eINSTANCE.getMain_Land();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.RecordedFlightImpl <em>Recorded Flight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.RecordedFlightImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRecordedFlight()
     * @generated
     */
    EClass RECORDED_FLIGHT = eINSTANCE.getRecordedFlight();

    /**
     * The meta object literal for the '<em><b>Video name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECORDED_FLIGHT__VIDEO_NAME = eINSTANCE.getRecordedFlight_Video_name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.UserFunctionImpl <em>User Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.UserFunctionImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getUserFunction()
     * @generated
     */
    EClass USER_FUNCTION = eINSTANCE.getUserFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute USER_FUNCTION__NAME = eINSTANCE.getUserFunction_Name();

    /**
     * The meta object literal for the '<em><b>Func</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference USER_FUNCTION__FUNC = eINSTANCE.getUserFunction_Func();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.FeatureMatchImpl <em>Feature Match</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.FeatureMatchImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getFeatureMatch()
     * @generated
     */
    EClass FEATURE_MATCH = eINSTANCE.getFeatureMatch();

    /**
     * The meta object literal for the '<em><b>Image name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE_MATCH__IMAGE_NAME = eINSTANCE.getFeatureMatch_Image_name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.SuperCommandImpl <em>Super Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.SuperCommandImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getSuperCommand()
     * @generated
     */
    EClass SUPER_COMMAND = eINSTANCE.getSuperCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.CommandImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.SnapshotImpl <em>Snapshot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.SnapshotImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getSnapshot()
     * @generated
     */
    EClass SNAPSHOT = eINSTANCE.getSnapshot();

    /**
     * The meta object literal for the '<em><b>Image name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SNAPSHOT__IMAGE_NAME = eINSTANCE.getSnapshot_Image_name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.UpImpl <em>Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.UpImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getUp()
     * @generated
     */
    EClass UP = eINSTANCE.getUp();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UP__MILLISECONDS = eINSTANCE.getUp_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.DownImpl <em>Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.DownImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getDown()
     * @generated
     */
    EClass DOWN = eINSTANCE.getDown();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DOWN__MILLISECONDS = eINSTANCE.getDown_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.LeftImpl <em>Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.LeftImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getLeft()
     * @generated
     */
    EClass LEFT = eINSTANCE.getLeft();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEFT__MILLISECONDS = eINSTANCE.getLeft_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.RightImpl <em>Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.RightImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRight()
     * @generated
     */
    EClass RIGHT = eINSTANCE.getRight();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RIGHT__MILLISECONDS = eINSTANCE.getRight_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.ForwardImpl <em>Forward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.ForwardImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getForward()
     * @generated
     */
    EClass FORWARD = eINSTANCE.getForward();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORWARD__MILLISECONDS = eINSTANCE.getForward_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.BackwardImpl <em>Backward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.BackwardImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getBackward()
     * @generated
     */
    EClass BACKWARD = eINSTANCE.getBackward();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BACKWARD__MILLISECONDS = eINSTANCE.getBackward_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.RotateLImpl <em>Rotate L</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.RotateLImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRotateL()
     * @generated
     */
    EClass ROTATE_L = eINSTANCE.getRotateL();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_L__MILLISECONDS = eINSTANCE.getRotateL_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.RotateRImpl <em>Rotate R</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.RotateRImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getRotateR()
     * @generated
     */
    EClass ROTATE_R = eINSTANCE.getRotateR();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_R__MILLISECONDS = eINSTANCE.getRotateR_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.WaitImpl <em>Wait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.WaitImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getWait()
     * @generated
     */
    EClass WAIT = eINSTANCE.getWait();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAIT__MILLISECONDS = eINSTANCE.getWait_Milliseconds();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.helloWeb.impl.FunctionNameImpl <em>Function Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.helloWeb.impl.FunctionNameImpl
     * @see org.xtext.example.mydsl.helloWeb.impl.HelloWebPackageImpl#getFunctionName()
     * @generated
     */
    EClass FUNCTION_NAME = eINSTANCE.getFunctionName();

    /**
     * The meta object literal for the '<em><b>Func name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION_NAME__FUNC_NAME = eINSTANCE.getFunctionName_Func_name();

  }

} //HelloWebPackage
