/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recorded Flight</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.helloWeb.RecordedFlight#getVideo_name <em>Video name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getRecordedFlight()
 * @model
 * @generated
 */
public interface RecordedFlight extends EObject
{
  /**
   * Returns the value of the '<em><b>Video name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Video name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Video name</em>' attribute.
   * @see #setVideo_name(String)
   * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getRecordedFlight_Video_name()
   * @model
   * @generated
   */
  String getVideo_name();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.helloWeb.RecordedFlight#getVideo_name <em>Video name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Video name</em>' attribute.
   * @see #getVideo_name()
   * @generated
   */
  void setVideo_name(String value);

} // RecordedFlight
