/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rotate L</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.helloWeb.RotateL#getAngle <em>Angle</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getRotateL()
 * @model
 * @generated
 */
public interface RotateL extends Command
{
  /**
   * Returns the value of the '<em><b>Angle</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Angle</em>' attribute.
   * @see #setAngle(int)
   * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getRotateL_Angle()
   * @model
   * @generated
   */
  int getAngle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.helloWeb.RotateL#getAngle <em>Angle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Angle</em>' attribute.
   * @see #getAngle()
   * @generated
   */
  void setAngle(int value);

} // RotateL
