/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Super Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getSuperCommand()
 * @model
 * @generated
 */
public interface SuperCommand extends EObject
{
} // SuperCommand
