/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Wait</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.helloWeb.Wait#getSeconds <em>Seconds</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getWait()
 * @model
 * @generated
 */
public interface Wait extends Command
{
  /**
   * Returns the value of the '<em><b>Seconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seconds</em>' attribute.
   * @see #setSeconds(String)
   * @see org.xtext.example.mydsl.helloWeb.HelloWebPackage#getWait_Seconds()
   * @model
   * @generated
   */
  String getSeconds();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.helloWeb.Wait#getSeconds <em>Seconds</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seconds</em>' attribute.
   * @see #getSeconds()
   * @generated
   */
  void setSeconds(String value);

} // Wait
