/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.helloWeb.Backward;
import org.xtext.example.mydsl.helloWeb.Down;
import org.xtext.example.mydsl.helloWeb.FeatureMatch;
import org.xtext.example.mydsl.helloWeb.Forward;
import org.xtext.example.mydsl.helloWeb.FunctionName;
import org.xtext.example.mydsl.helloWeb.HelloWebPackage;
import org.xtext.example.mydsl.helloWeb.Left;
import org.xtext.example.mydsl.helloWeb.Main;
import org.xtext.example.mydsl.helloWeb.Program;
import org.xtext.example.mydsl.helloWeb.RecordedFlight;
import org.xtext.example.mydsl.helloWeb.Right;
import org.xtext.example.mydsl.helloWeb.RotateL;
import org.xtext.example.mydsl.helloWeb.RotateR;
import org.xtext.example.mydsl.helloWeb.Snapshot;
import org.xtext.example.mydsl.helloWeb.Up;
import org.xtext.example.mydsl.helloWeb.UserFunction;
import org.xtext.example.mydsl.helloWeb.Wait;
import org.xtext.example.mydsl.services.HelloWebGrammarAccess;

@SuppressWarnings("all")
public class HelloWebSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private HelloWebGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == HelloWebPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case HelloWebPackage.BACKWARD:
				sequence_Backward(context, (Backward) semanticObject); 
				return; 
			case HelloWebPackage.DOWN:
				sequence_Down(context, (Down) semanticObject); 
				return; 
			case HelloWebPackage.FEATURE_MATCH:
				sequence_FeatureMatch(context, (FeatureMatch) semanticObject); 
				return; 
			case HelloWebPackage.FORWARD:
				sequence_Forward(context, (Forward) semanticObject); 
				return; 
			case HelloWebPackage.FUNCTION_NAME:
				sequence_FunctionName(context, (FunctionName) semanticObject); 
				return; 
			case HelloWebPackage.LEFT:
				sequence_Left(context, (Left) semanticObject); 
				return; 
			case HelloWebPackage.MAIN:
				sequence_Main(context, (Main) semanticObject); 
				return; 
			case HelloWebPackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case HelloWebPackage.RECORDED_FLIGHT:
				sequence_RecordedFlight(context, (RecordedFlight) semanticObject); 
				return; 
			case HelloWebPackage.RIGHT:
				sequence_Right(context, (Right) semanticObject); 
				return; 
			case HelloWebPackage.ROTATE_L:
				sequence_RotateL(context, (RotateL) semanticObject); 
				return; 
			case HelloWebPackage.ROTATE_R:
				sequence_RotateR(context, (RotateR) semanticObject); 
				return; 
			case HelloWebPackage.SNAPSHOT:
				sequence_Snapshot(context, (Snapshot) semanticObject); 
				return; 
			case HelloWebPackage.UP:
				sequence_Up(context, (Up) semanticObject); 
				return; 
			case HelloWebPackage.USER_FUNCTION:
				sequence_UserFunction(context, (UserFunction) semanticObject); 
				return; 
			case HelloWebPackage.WAIT:
				sequence_Wait(context, (Wait) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     SuperCommand returns Backward
	 *     Command returns Backward
	 *     Backward returns Backward
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_Backward(ISerializationContext context, Backward semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.BACKWARD__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.BACKWARD__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getBackwardAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns Down
	 *     Command returns Down
	 *     Down returns Down
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_Down(ISerializationContext context, Down semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.DOWN__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.DOWN__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDownAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     FeatureMatch returns FeatureMatch
	 *
	 * Constraint:
	 *     image_name=ID
	 */
	protected void sequence_FeatureMatch(ISerializationContext context, FeatureMatch semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.FEATURE_MATCH__IMAGE_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.FEATURE_MATCH__IMAGE_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFeatureMatchAccess().getImage_nameIDTerminalRuleCall_2_0(), semanticObject.getImage_name());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns Forward
	 *     Command returns Forward
	 *     Forward returns Forward
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_Forward(ISerializationContext context, Forward semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.FORWARD__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.FORWARD__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getForwardAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns FunctionName
	 *     FunctionName returns FunctionName
	 *
	 * Constraint:
	 *     func_name=ID
	 */
	protected void sequence_FunctionName(ISerializationContext context, FunctionName semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.FUNCTION_NAME__FUNC_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.FUNCTION_NAME__FUNC_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFunctionNameAccess().getFunc_nameIDTerminalRuleCall_0_0(), semanticObject.getFunc_name());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns Left
	 *     Command returns Left
	 *     Left returns Left
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_Left(ISerializationContext context, Left semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.LEFT__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.LEFT__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLeftAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Main returns Main
	 *
	 * Constraint:
	 *     (commands+=Snapshot | (commands+=Snapshot takeoff+=Takeoff commands+=SuperCommand* land+=Land))?
	 */
	protected void sequence_Main(ISerializationContext context, Main semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     main=Main
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.PROGRAM__MAIN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.PROGRAM__MAIN));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getProgramAccess().getMainMainParserRuleCall_0(), semanticObject.getMain());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     RecordedFlight returns RecordedFlight
	 *
	 * Constraint:
	 *     video_name=ID
	 */
	protected void sequence_RecordedFlight(ISerializationContext context, RecordedFlight semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.RECORDED_FLIGHT__VIDEO_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.RECORDED_FLIGHT__VIDEO_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRecordedFlightAccess().getVideo_nameIDTerminalRuleCall_2_0(), semanticObject.getVideo_name());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns Right
	 *     Command returns Right
	 *     Right returns Right
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_Right(ISerializationContext context, Right semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.RIGHT__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.RIGHT__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRightAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns RotateL
	 *     Command returns RotateL
	 *     RotateL returns RotateL
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_RotateL(ISerializationContext context, RotateL semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.ROTATE_L__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.ROTATE_L__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRotateLAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns RotateR
	 *     Command returns RotateR
	 *     RotateR returns RotateR
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_RotateR(ISerializationContext context, RotateR semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.ROTATE_R__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.ROTATE_R__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRotateRAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns Snapshot
	 *     Command returns Snapshot
	 *     Snapshot returns Snapshot
	 *
	 * Constraint:
	 *     image_name=ID
	 */
	protected void sequence_Snapshot(ISerializationContext context, Snapshot semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.SNAPSHOT__IMAGE_NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.SNAPSHOT__IMAGE_NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSnapshotAccess().getImage_nameIDTerminalRuleCall_2_0(), semanticObject.getImage_name());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns Up
	 *     Command returns Up
	 *     Up returns Up
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_Up(ISerializationContext context, Up semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.UP__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.UP__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getUpAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     UserFunction returns UserFunction
	 *
	 * Constraint:
	 *     (name=ID func+=Command*)
	 */
	protected void sequence_UserFunction(ISerializationContext context, UserFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SuperCommand returns Wait
	 *     Command returns Wait
	 *     Wait returns Wait
	 *
	 * Constraint:
	 *     milliseconds=INT
	 */
	protected void sequence_Wait(ISerializationContext context, Wait semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, HelloWebPackage.Literals.WAIT__MILLISECONDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HelloWebPackage.Literals.WAIT__MILLISECONDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWaitAccess().getMillisecondsINTTerminalRuleCall_2_0(), semanticObject.getMilliseconds());
		feeder.finish();
	}
	
	
}
