/*
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.helloweb.ui.internal.HellowebActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HelloWebExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(HellowebActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		HellowebActivator activator = HellowebActivator.getInstance();
		return activator != null ? activator.getInjector(HellowebActivator.ORG_XTEXT_EXAMPLE_MYDSL_HELLOWEB) : null;
	}

}
