/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.ide;

import org.xtext.example.mydsl.ide.AbstractHelloWebIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class HelloWebIdeModule extends AbstractHelloWebIdeModule {
}
