/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;
import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.helloWeb.HelloWebPackage;
import org.xtext.example.mydsl.helloWeb.Main;
import org.xtext.example.mydsl.helloWeb.SuperCommand;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.helloWeb.impl.MainImpl#getCommands <em>Commands</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.helloWeb.impl.MainImpl#getTakeoff <em>Takeoff</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.helloWeb.impl.MainImpl#getLand <em>Land</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MainImpl extends MinimalEObjectImpl.Container implements Main
{
  /**
   * The cached value of the '{@link #getCommands() <em>Commands</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommands()
   * @generated
   * @ordered
   */
  protected EList<SuperCommand> commands;

  /**
   * The cached value of the '{@link #getTakeoff() <em>Takeoff</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTakeoff()
   * @generated
   * @ordered
   */
  protected EList<String> takeoff;

  /**
   * The cached value of the '{@link #getLand() <em>Land</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLand()
   * @generated
   * @ordered
   */
  protected EList<String> land;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HelloWebPackage.Literals.MAIN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<SuperCommand> getCommands()
  {
    if (commands == null)
    {
      commands = new EObjectContainmentEList<SuperCommand>(SuperCommand.class, this, HelloWebPackage.MAIN__COMMANDS);
    }
    return commands;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getTakeoff()
  {
    if (takeoff == null)
    {
      takeoff = new EDataTypeEList<String>(String.class, this, HelloWebPackage.MAIN__TAKEOFF);
    }
    return takeoff;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<String> getLand()
  {
    if (land == null)
    {
      land = new EDataTypeEList<String>(String.class, this, HelloWebPackage.MAIN__LAND);
    }
    return land;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HelloWebPackage.MAIN__COMMANDS:
        return ((InternalEList<?>)getCommands()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HelloWebPackage.MAIN__COMMANDS:
        return getCommands();
      case HelloWebPackage.MAIN__TAKEOFF:
        return getTakeoff();
      case HelloWebPackage.MAIN__LAND:
        return getLand();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HelloWebPackage.MAIN__COMMANDS:
        getCommands().clear();
        getCommands().addAll((Collection<? extends SuperCommand>)newValue);
        return;
      case HelloWebPackage.MAIN__TAKEOFF:
        getTakeoff().clear();
        getTakeoff().addAll((Collection<? extends String>)newValue);
        return;
      case HelloWebPackage.MAIN__LAND:
        getLand().clear();
        getLand().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HelloWebPackage.MAIN__COMMANDS:
        getCommands().clear();
        return;
      case HelloWebPackage.MAIN__TAKEOFF:
        getTakeoff().clear();
        return;
      case HelloWebPackage.MAIN__LAND:
        getLand().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HelloWebPackage.MAIN__COMMANDS:
        return commands != null && !commands.isEmpty();
      case HelloWebPackage.MAIN__TAKEOFF:
        return takeoff != null && !takeoff.isEmpty();
      case HelloWebPackage.MAIN__LAND:
        return land != null && !land.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (takeoff: ");
    result.append(takeoff);
    result.append(", land: ");
    result.append(land);
    result.append(')');
    return result.toString();
  }

} //MainImpl
