/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.helloWeb.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.helloWeb.HelloWebPackage;
import org.xtext.example.mydsl.helloWeb.SuperCommand;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Super Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SuperCommandImpl extends MinimalEObjectImpl.Container implements SuperCommand
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SuperCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HelloWebPackage.Literals.SUPER_COMMAND;
  }

} //SuperCommandImpl
